include:
- ./functions/allfire.zip
kind: ArchiveUploadSpec
name: functions-allfire-zip-qFEo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: allfire
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-allfire-zip-qFEo
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-08T11:19:40Z"
