include:
- ./functions/bushfire.zip
kind: ArchiveUploadSpec
name: functions-bushfire-zip-AnaB

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bushfire1
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-bushfire-zip-AnaB
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-07T12:23:23Z"
