include:
- ./functions/airquality.zip
kind: ArchiveUploadSpec
name: functions-airquality-zip-8y8Q

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: airquality
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-airquality-zip-8y8Q
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-13T06:33:54Z"
