apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: test-airquality
spec:
  createingress: true
  functionref:
    functionweights: null
    name: airquality
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /collect-air-quality-data/test/{test:[tf]}/siteid/{siteid:[0-9]+}/startmonth/{startmonth:[0-9]{4}-[0-1][0-9]}/endmonth/{endmonth:[0-9]{4}-[0-1][0-9]}
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /collect-air-quality-data/test/{test:[tf]}/siteid/{siteid:[0-9]+}/startmonth/{startmonth:[0-9]{4}-[0-1][0-9]}/endmonth/{endmonth:[0-9]{4}-[0-1][0-9]}
