include:
- ./functions/toots-getter.zip
kind: ArchiveUploadSpec
name: functions-toots-getter-zip-AAYb

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: toots-getter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-toots-getter-zip-AAYb
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T04:29:06Z"
