apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: nsw-month-admissions
spec:
  createingress: true
  functionref:
    functionweights: null
    name: admissions
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /admissions/nsw/years/{year:[0-9][0-9][0-9][0-9]}/months/{month:[0-9]{1,2}}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /admissions/nsw/years/{year:[0-9][0-9][0-9][0-9]}/months/{month:[0-9]{1,2}}
