apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: admissions
spec:
  createingress: true
  functionref:
    functionweights: null
    name: admissions
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /admissions
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /admissions
