apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: pha-admissions
spec:
  createingress: true
  functionref:
    functionweights: null
    name: admissions
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /admissions/phas/{pha:[0-9]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /admissions/phas/{pha:[0-9]+}
