include:
- ./functions/airquality-getter.zip
kind: ArchiveUploadSpec
name: functions-airquality-getter-zip-ZiBf

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: airquality-getter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-airquality-getter-zip-ZiBf
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-13T07:00:44Z"
