apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getairqualitysiteyearmonth
spec:
  createingress: true
  functionref:
    functionweights: null
    name: airquality-getter
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /getairquality/siteid/{siteid:[0-9]+}/year/{year:[0-9]{4}}/month/{month:[0-1][0-9]}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /getairquality/siteid/{siteid:[0-9]+}/year/{year:[0-9]{4}}/month/{month:[0-1][0-9]}
