apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: getaverageairqualityyear
spec:
  createingress: true
  functionref:
    functionweights: null
    name: airquality-getter
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /getairquality/year/{year:[0-9]{4}}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /getairquality/year/{year:[0-9]{4}}
