include:
- ./combine-bushfire.zip
kind: ArchiveUploadSpec
name: combine-bushfire-zip-QN8Z

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: combine-bushfire
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://combine-bushfire-zip-QN8Z
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T05:02:51Z"
