apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: combine-bushfire
spec:
  createingress: true
  functionref:
    functionweights: null
    name: combine-bushfire
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /combine-bushfire/start/{start:[0-9][0-9][0-9][0-9]}/end/{end:[0-9][0-9][0-9][0-9]}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /combine-bushfire/start/{start:[0-9][0-9][0-9][0-9]}/end/{end:[0-9][0-9][0-9][0-9]}
