include:
- ./functions/addtoots.zip
kind: ArchiveUploadSpec
name: functions-addtoots-zip-Xyk1

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addtoots
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-addtoots-zip-Xyk1
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-11T06:13:46Z"
